[package]
name = "v_escape"
version = "0.5.0"
authors = ["Rust-iendo Barcelona <riendocontributions@gmail.com>"]
description = "The simd optimized escaping code"
documentation = "https://docs.rs/v_escape"
keywords = ["escaping", "simd"]
homepage = "https://github.com/rust-iendo/v_htmlescape"
repository = "https://github.com/rust-iendo/v_htmlescape"
license = "MIT/Apache-2.0"
readme = "README.md"
workspace = ".."
edition = "2018"

[badges]
appveyor = { repository = "botika/v_htmlescape" }
maintenance = { status = "actively-developed" }
travis-ci = { repository =  "rust-iendo/v_htmlescape", branch = "master" }
codecov = { repository = "rust-iendo/v_htmlescape", branch = "master", service = "github" }

[lib]
name = "v_escape"
path = "src/lib.rs"
bench = false

[dependencies]
v_escape_derive = { version = "0.4", path = "../v_escape_derive" }

[build-dependencies]
version_check = "0.1"
